---

- name: Retrieving Security Attributes
  infn_tl1:
    provider: "{{ tl1 }}"
    commands_and_inputs: "{{ lookup('template', 'retrieve_security_attributes.j2') }}"
    output: "json"
    save: "{{ module_save_file | default('infn_tl1') }}.txt"
  register: rtrv_sec_attr_res
  changed_when: false
  failed_when: rtrv_sec_attr_res.status == "FAILURE"

- name: Renaming Raw Response Parameters
  infn_mapper:
    mapper: "{{ security_attributes_mapper }}"
    tl1_response: "{{ rtrv_sec_attr_res }}"
  register: mapped_rtrv_res
  when:
    - security_attributes_mapper is defined

- name: Result of the retrieval
  debug:
    msg: "{%- if mapped_rtrv_res.skipped | default(false) -%}{{- rtrv_sec_attr_res -}}{%- else -%}{{- mapped_rtrv_res -}}{%- endif -%}"
